

const projects = [
  {
    id: 1,
    name: "Tamagrow",
    edgyName: "/TAMAGROW.IO",
    description: `Tamagrow is our solution for a more **price-accessible** video game cosmetic experience. Users are provided an **immersive experience** to increase gaming productivity across all of their favorite titles.`,
    tags: ["Game", "Desktop", "Design"],
    link: "/project/1",
    coverImg: "/img/tamagrow.png",
    logoImg: "/img/tamagrow_logo.png",
    numberSrc: "/img/numbers/1.svg",
    hoverSrc: "/img/numbers/filled/1.svg",
    gradientColor: "bg-gradient-to-b from-violet-950",

  },
  {
    id: 2,
    name: "RKK",
    edgyName: "/RKK SOLUTIONS",
    description: "RKK Solutions is our in-house **digital transformation** team, committed to developing tech solutions for local businesses in the Seattle area. Our expertise encompasses a wide range of services designed to **elevate** your digital presence and streamline operations.",
    tags: ["Web", "Agency", "Design"],
    link: "/project/2",
    coverImg: "/img/rkk.png",
    logoImg: "/img/rkk_logo.png",
    numberSrc: "/img/numbers/2.svg",
    hoverSrc: "/img/numbers/filled/2.svg",
    gradientColor: "purple"
  },
  {
    id: 3,
    name: "Kual Notes",
    edgyName: "/KUAL NOTES",
    description: "Kual Notes is a personal diary that provides resources and tips based on a sentiment analysis of your journal entries. Developed for the University of Washinton ProSeed Hackathon. \n Kual Notes was developed as a mobile app, utilizing Symbl.ai's sentiment analysis tools.",
    tags: ["Web", "Design", "Agency"],
    link: "/project/3",
    coverImg: "/img/kualnotes.png",
    logoImg: "/img/kualnotes_logo.png",
    numberSrc: "/img/numbers/3.svg",
    hoverSrc: "/img/numbers/filled/3.svg",
  },
  {
    id: 4,
    name: "Poke Dokey",
    edgyName: "/POKEDOKEY",
    description: "Poke Dokey is Hawaiian-theme brick breaker currently being developed for iOS devices. \n We don't have too much to show for it at the moment but take a look at some screenshots:",
    tags: ["Web", "Design"],
    link: "/project/4",
    coverImg: "/img/pokedokey.png",
    logoImg: "/img/pokedokey_logo.png",
    numberSrc: "/img/numbers/4.svg",
    hoverSrc: "/img/numbers/filled/4.svg",
    
  },
  {
    id: 5,
    name: "OZPlay",
    edgyName: "/OZPLAY",
    description: "OZPlay is a proprietary overlay service currently in development. \n Stay tuned for more.",
    tags: ["Web", "Design"],
    link: "/project/5",
    coverImg: "/img/ozplay.png",
    logoImg: "/img/ozplay_logo.png",
    numberSrc: "/img/numbers/5.svg",
    hoverSrc: "/img/numbers/filled/5.svg",
  },
  {
    id: 6,
    name: "More",
    edgyName: "/MORE",
    description: "Here's a gallery of other projects we've done:",
    tags: ["Design"],
    link: "/project/6",
    coverImg: "/img/more.png",
    logoImg: null,
    numberSrc: "/img/numbers/6.svg",
    hoverSrc: "/img/numbers/filled/6.svg",
  },
];

export { projects };
